// flow-typed signature: f66eb6953fca311ac10523647e8d9dba
// flow-typed version: <<STUB>>/blangko_v^0.0.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blangko'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blangko' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blangko/build/index' {
  declare module.exports: any;
}

declare module 'blangko/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blangko/build/index.js' {
  declare module.exports: $Exports<'blangko/build/index'>;
}
declare module 'blangko/webpack.config.babel.js' {
  declare module.exports: $Exports<'blangko/webpack.config.babel'>;
}
