// flow-typed signature: dd4cd5f13fcc5f44babfc04fe7eb265f
// flow-typed version: <<STUB>>/react-breadcrumbs_v^1.6.6/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-breadcrumbs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-breadcrumbs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-breadcrumbs/demo/app' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/index' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/routes' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/dist/react-breadcrumbs.min' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/test/usersRoute' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-breadcrumbs/demo/app.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/app'>;
}
declare module 'react-breadcrumbs/demo/dist/bundle.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/dist/bundle'>;
}
declare module 'react-breadcrumbs/demo/index.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/index'>;
}
declare module 'react-breadcrumbs/demo/routes.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/routes'>;
}
declare module 'react-breadcrumbs/demo/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/webpack.config.dev'>;
}
declare module 'react-breadcrumbs/demo/webpack.config.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/webpack.config'>;
}
declare module 'react-breadcrumbs/dist/react-breadcrumbs.min.js' {
  declare module.exports: $Exports<'react-breadcrumbs/dist/react-breadcrumbs.min'>;
}
declare module 'react-breadcrumbs/index' {
  declare module.exports: $Exports<'react-breadcrumbs'>;
}
declare module 'react-breadcrumbs/index.js' {
  declare module.exports: $Exports<'react-breadcrumbs'>;
}
declare module 'react-breadcrumbs/index' {
  declare module.exports: $Exports<'react-breadcrumbs'>;
}
declare module 'react-breadcrumbs/index.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs'>;
}
declare module 'react-breadcrumbs/test/usersRoute.js' {
  declare module.exports: $Exports<'react-breadcrumbs/test/usersRoute'>;
}
