// flow-typed signature: 189eb6ac7f3306bc44b0b70050e9dfad
// flow-typed version: <<STUB>>/react-loading_v0.0.9/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading/dist/react-loading' {
  declare module.exports: any;
}

declare module 'react-loading/lib/react-loading' {
  declare module.exports: any;
}

declare module 'react-loading/lib/svg/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading/dist/react-loading.js' {
  declare module.exports: $Exports<'react-loading/dist/react-loading'>;
}
declare module 'react-loading/lib/react-loading.js' {
  declare module.exports: $Exports<'react-loading/lib/react-loading'>;
}
declare module 'react-loading/lib/svg/index.js' {
  declare module.exports: $Exports<'react-loading/lib/svg/index'>;
}
