// flow-typed signature: 47c5bbc3e922e64bbb2fdc523e3a5f63
// flow-typed version: <<STUB>>/react-d3-cloud_v^0.4.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-d3-cloud'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-d3-cloud' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-d3-cloud/examples/basic/src/index' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/examples/basic/webpack.config' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/__test__/WordCloud.spec' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/__tests__/WordCloud.spec' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/defaultMappers/defaultFontSizeMapper' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/defaultMappers/defaultRotate' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/defaultMappers/index' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/index' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/lib/WordCloud' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/__tests__/WordCloud.spec' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/__tests__/WordCloud.updateProps.spec' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/defaultMappers/defaultFontSizeMapper' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/defaultMappers/index' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/index' {
  declare module.exports: any;
}

declare module 'react-d3-cloud/src/WordCloud' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-d3-cloud/examples/basic/src/index.js' {
  declare module.exports: $Exports<'react-d3-cloud/examples/basic/src/index'>;
}
declare module 'react-d3-cloud/examples/basic/webpack.config.js' {
  declare module.exports: $Exports<'react-d3-cloud/examples/basic/webpack.config'>;
}
declare module 'react-d3-cloud/lib/__test__/WordCloud.spec.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/__test__/WordCloud.spec'>;
}
declare module 'react-d3-cloud/lib/__tests__/WordCloud.spec.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/__tests__/WordCloud.spec'>;
}
declare module 'react-d3-cloud/lib/defaultMappers/defaultFontSizeMapper.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/defaultMappers/defaultFontSizeMapper'>;
}
declare module 'react-d3-cloud/lib/defaultMappers/defaultRotate.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/defaultMappers/defaultRotate'>;
}
declare module 'react-d3-cloud/lib/defaultMappers/index.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/defaultMappers/index'>;
}
declare module 'react-d3-cloud/lib/index.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/index'>;
}
declare module 'react-d3-cloud/lib/WordCloud.js' {
  declare module.exports: $Exports<'react-d3-cloud/lib/WordCloud'>;
}
declare module 'react-d3-cloud/src/__tests__/WordCloud.spec.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/__tests__/WordCloud.spec'>;
}
declare module 'react-d3-cloud/src/__tests__/WordCloud.updateProps.spec.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/__tests__/WordCloud.updateProps.spec'>;
}
declare module 'react-d3-cloud/src/defaultMappers/defaultFontSizeMapper.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/defaultMappers/defaultFontSizeMapper'>;
}
declare module 'react-d3-cloud/src/defaultMappers/index.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/defaultMappers/index'>;
}
declare module 'react-d3-cloud/src/index.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/index'>;
}
declare module 'react-d3-cloud/src/WordCloud.js' {
  declare module.exports: $Exports<'react-d3-cloud/src/WordCloud'>;
}
