// flow-typed signature: 9af907cc75a8cc830adb6a9ec61b8c0d
// flow-typed version: <<STUB>>/rxdb_v^4.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rxdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rxdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rxdb/config/gulpfile' {
  declare module.exports: any;
}

declare module 'rxdb/config/karma.conf' {
  declare module.exports: any;
}

declare module 'rxdb/config/rollup.config' {
  declare module.exports: any;
}

declare module 'rxdb/config/webpack.config' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/ChangeEventBuffer' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/Crypter' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/DataMigrator' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/DocCache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/KeyCompressor' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/LeaderElector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/PouchDB' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/QueryCache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/QueryChangeDetector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxBroadcastChannel' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxChangeEvent' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxCollection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxDatabase' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxDocument' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxQuery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/RxSchema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/Socket' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/util' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/ChangeEventBuffer' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/Crypter' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/DataMigrator' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/DocCache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/KeyCompressor' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/LeaderElector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/PouchDB' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/QueryCache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/QueryChangeDetector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxBroadcastChannel' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxChangeEvent' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxCollection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxDatabase' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxDocument' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxQuery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxSchema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/Socket' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/util' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify.min' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/index' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils' {
  declare module.exports: any;
}

declare module 'rxdb/scripts/transpile' {
  declare module.exports: any;
}

declare module 'rxdb/src/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/src/ChangeEventBuffer' {
  declare module.exports: any;
}

declare module 'rxdb/src/Crypter' {
  declare module.exports: any;
}

declare module 'rxdb/src/DataMigrator' {
  declare module.exports: any;
}

declare module 'rxdb/src/DocCache' {
  declare module.exports: any;
}

declare module 'rxdb/src/index' {
  declare module.exports: any;
}

declare module 'rxdb/src/KeyCompressor' {
  declare module.exports: any;
}

declare module 'rxdb/src/LeaderElector' {
  declare module.exports: any;
}

declare module 'rxdb/src/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/src/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/src/PouchDB' {
  declare module.exports: any;
}

declare module 'rxdb/src/QueryCache' {
  declare module.exports: any;
}

declare module 'rxdb/src/QueryChangeDetector' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxBroadcastChannel' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxChangeEvent' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxCollection' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxDatabase' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxDocument' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxQuery' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxSchema' {
  declare module.exports: any;
}

declare module 'rxdb/src/Socket' {
  declare module.exports: any;
}

declare module 'rxdb/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rxdb/config/gulpfile.js' {
  declare module.exports: $Exports<'rxdb/config/gulpfile'>;
}
declare module 'rxdb/config/karma.conf.js' {
  declare module.exports: $Exports<'rxdb/config/karma.conf'>;
}
declare module 'rxdb/config/rollup.config.js' {
  declare module.exports: $Exports<'rxdb/config/rollup.config'>;
}
declare module 'rxdb/config/webpack.config.js' {
  declare module.exports: $Exports<'rxdb/config/webpack.config'>;
}
declare module 'rxdb/dist/es/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/dist/es/browserify.index'>;
}
declare module 'rxdb/dist/es/ChangeEventBuffer.js' {
  declare module.exports: $Exports<'rxdb/dist/es/ChangeEventBuffer'>;
}
declare module 'rxdb/dist/es/Crypter.js' {
  declare module.exports: $Exports<'rxdb/dist/es/Crypter'>;
}
declare module 'rxdb/dist/es/DataMigrator.js' {
  declare module.exports: $Exports<'rxdb/dist/es/DataMigrator'>;
}
declare module 'rxdb/dist/es/DocCache.js' {
  declare module.exports: $Exports<'rxdb/dist/es/DocCache'>;
}
declare module 'rxdb/dist/es/index.js' {
  declare module.exports: $Exports<'rxdb/dist/es/index'>;
}
declare module 'rxdb/dist/es/KeyCompressor.js' {
  declare module.exports: $Exports<'rxdb/dist/es/KeyCompressor'>;
}
declare module 'rxdb/dist/es/LeaderElector.js' {
  declare module.exports: $Exports<'rxdb/dist/es/LeaderElector'>;
}
declare module 'rxdb/dist/es/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/dist/es/mquery/mquery_utils'>;
}
declare module 'rxdb/dist/es/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/dist/es/mquery/mquery'>;
}
declare module 'rxdb/dist/es/PouchDB.js' {
  declare module.exports: $Exports<'rxdb/dist/es/PouchDB'>;
}
declare module 'rxdb/dist/es/QueryCache.js' {
  declare module.exports: $Exports<'rxdb/dist/es/QueryCache'>;
}
declare module 'rxdb/dist/es/QueryChangeDetector.js' {
  declare module.exports: $Exports<'rxdb/dist/es/QueryChangeDetector'>;
}
declare module 'rxdb/dist/es/RxBroadcastChannel.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxBroadcastChannel'>;
}
declare module 'rxdb/dist/es/RxChangeEvent.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxChangeEvent'>;
}
declare module 'rxdb/dist/es/RxCollection.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxCollection'>;
}
declare module 'rxdb/dist/es/RxDatabase.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxDatabase'>;
}
declare module 'rxdb/dist/es/RxDocument.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxDocument'>;
}
declare module 'rxdb/dist/es/RxQuery.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxQuery'>;
}
declare module 'rxdb/dist/es/RxSchema.js' {
  declare module.exports: $Exports<'rxdb/dist/es/RxSchema'>;
}
declare module 'rxdb/dist/es/Socket.js' {
  declare module.exports: $Exports<'rxdb/dist/es/Socket'>;
}
declare module 'rxdb/dist/es/util.js' {
  declare module.exports: $Exports<'rxdb/dist/es/util'>;
}
declare module 'rxdb/dist/lib/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/browserify.index'>;
}
declare module 'rxdb/dist/lib/ChangeEventBuffer.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/ChangeEventBuffer'>;
}
declare module 'rxdb/dist/lib/Crypter.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/Crypter'>;
}
declare module 'rxdb/dist/lib/DataMigrator.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/DataMigrator'>;
}
declare module 'rxdb/dist/lib/DocCache.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/DocCache'>;
}
declare module 'rxdb/dist/lib/index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/index'>;
}
declare module 'rxdb/dist/lib/KeyCompressor.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/KeyCompressor'>;
}
declare module 'rxdb/dist/lib/LeaderElector.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/LeaderElector'>;
}
declare module 'rxdb/dist/lib/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery_utils'>;
}
declare module 'rxdb/dist/lib/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery'>;
}
declare module 'rxdb/dist/lib/PouchDB.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/PouchDB'>;
}
declare module 'rxdb/dist/lib/QueryCache.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/QueryCache'>;
}
declare module 'rxdb/dist/lib/QueryChangeDetector.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/QueryChangeDetector'>;
}
declare module 'rxdb/dist/lib/RxBroadcastChannel.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxBroadcastChannel'>;
}
declare module 'rxdb/dist/lib/RxChangeEvent.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxChangeEvent'>;
}
declare module 'rxdb/dist/lib/RxCollection.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxCollection'>;
}
declare module 'rxdb/dist/lib/RxDatabase.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxDatabase'>;
}
declare module 'rxdb/dist/lib/RxDocument.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxDocument'>;
}
declare module 'rxdb/dist/lib/RxQuery.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxQuery'>;
}
declare module 'rxdb/dist/lib/RxSchema.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxSchema'>;
}
declare module 'rxdb/dist/lib/Socket.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/Socket'>;
}
declare module 'rxdb/dist/lib/util.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/util'>;
}
declare module 'rxdb/dist/rxdb.browserify.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify'>;
}
declare module 'rxdb/dist/rxdb.browserify.min.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify.min'>;
}
declare module 'rxdb/plugins/adapter-localstorage/index.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/index'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils'>;
}
declare module 'rxdb/scripts/transpile.js' {
  declare module.exports: $Exports<'rxdb/scripts/transpile'>;
}
declare module 'rxdb/src/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/src/browserify.index'>;
}
declare module 'rxdb/src/ChangeEventBuffer.js' {
  declare module.exports: $Exports<'rxdb/src/ChangeEventBuffer'>;
}
declare module 'rxdb/src/Crypter.js' {
  declare module.exports: $Exports<'rxdb/src/Crypter'>;
}
declare module 'rxdb/src/DataMigrator.js' {
  declare module.exports: $Exports<'rxdb/src/DataMigrator'>;
}
declare module 'rxdb/src/DocCache.js' {
  declare module.exports: $Exports<'rxdb/src/DocCache'>;
}
declare module 'rxdb/src/index.js' {
  declare module.exports: $Exports<'rxdb/src/index'>;
}
declare module 'rxdb/src/KeyCompressor.js' {
  declare module.exports: $Exports<'rxdb/src/KeyCompressor'>;
}
declare module 'rxdb/src/LeaderElector.js' {
  declare module.exports: $Exports<'rxdb/src/LeaderElector'>;
}
declare module 'rxdb/src/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/src/mquery/mquery_utils'>;
}
declare module 'rxdb/src/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/src/mquery/mquery'>;
}
declare module 'rxdb/src/PouchDB.js' {
  declare module.exports: $Exports<'rxdb/src/PouchDB'>;
}
declare module 'rxdb/src/QueryCache.js' {
  declare module.exports: $Exports<'rxdb/src/QueryCache'>;
}
declare module 'rxdb/src/QueryChangeDetector.js' {
  declare module.exports: $Exports<'rxdb/src/QueryChangeDetector'>;
}
declare module 'rxdb/src/RxBroadcastChannel.js' {
  declare module.exports: $Exports<'rxdb/src/RxBroadcastChannel'>;
}
declare module 'rxdb/src/RxChangeEvent.js' {
  declare module.exports: $Exports<'rxdb/src/RxChangeEvent'>;
}
declare module 'rxdb/src/RxCollection.js' {
  declare module.exports: $Exports<'rxdb/src/RxCollection'>;
}
declare module 'rxdb/src/RxDatabase.js' {
  declare module.exports: $Exports<'rxdb/src/RxDatabase'>;
}
declare module 'rxdb/src/RxDocument.js' {
  declare module.exports: $Exports<'rxdb/src/RxDocument'>;
}
declare module 'rxdb/src/RxQuery.js' {
  declare module.exports: $Exports<'rxdb/src/RxQuery'>;
}
declare module 'rxdb/src/RxSchema.js' {
  declare module.exports: $Exports<'rxdb/src/RxSchema'>;
}
declare module 'rxdb/src/Socket.js' {
  declare module.exports: $Exports<'rxdb/src/Socket'>;
}
declare module 'rxdb/src/util.js' {
  declare module.exports: $Exports<'rxdb/src/util'>;
}
